# Generated by Django 5.1.7 on 2025-04-05 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blog_post',
        ),
    ]
