# Generated by Django 5.1.7 on 2025-04-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages_app', '0002_rename_blog_blog_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=120)),
                ('image_blog', models.ImageField(upload_to='images/')),
                ('message', models.TextField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog_post',
        ),
    ]
